import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { Navbar } from "@/components/navbar/navbar";
import { LanguageProviderWrapper } from "@/components/LanguageProviderWrapper";

export const metadata: Metadata = {
  title: "Kazi up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[#070F2B]`}
      >
        <ReduxProvider>
          <LanguageProviderWrapper>
            <Navbar />
            {children}
          </LanguageProviderWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
