import { AdminNavbar } from "@/components/navbar/adminNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kazi up",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`bg-[#070F2B] fixed left-0 top-0 z-50 w-full h-screen`}
    >
      <AdminNavbar/>
      {children}
    </div>
  );
}
